<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Agenda extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Agenda_model');
    } 

    /*
     * Listing of agenda
     */
    function index()
    {
        $data['agenda'] = $this->Agenda_model->get_all_agenda();
        
        $data['_view'] = 'agenda/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new agenda
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
				'date' => $this->input->post('date'),
            );
            
            $agenda_id = $this->Agenda_model->add_agenda($params);
            redirect('agenda/index');
        }
        else
        {            
            $data['_view'] = 'agenda/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a agenda
     */
    function edit($id)
    {   
        // check if the agenda exists before trying to edit it
        $data['agenda'] = $this->Agenda_model->get_agenda($id);
        
        if(isset($data['agenda']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
					'date' => $this->input->post('date'),
                );

                $this->Agenda_model->update_agenda($id,$params);            
                redirect('agenda/index');
            }
            else
            {
                $data['_view'] = 'agenda/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The agenda you are trying to edit does not exist.');
    } 

    /*
     * Deleting agenda
     */
    function remove($id)
    {
        $agenda = $this->Agenda_model->get_agenda($id);

        // check if the agenda exists before trying to delete it
        if(isset($agenda['id']))
        {
            $this->Agenda_model->delete_agenda($id);
            redirect('agenda/index');
        }
        else
            show_error('The agenda you are trying to delete does not exist.');
    }
    
}
