<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Beritum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Beritum_model');
    } 

    /*
     * Listing of berita
     */
    function index()
    {
        $data['berita'] = $this->Beritum_model->get_all_berita();
        
        $data['_view'] = 'beritum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new beritum
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'judul' => $this->input->post('judul'),
				'content' => $this->input->post('content'),
				'gambar' => $this->input->post('gambar'),
				'date' => $this->input->post('date'),
            );
            
            $beritum_id = $this->Beritum_model->add_beritum($params);
            redirect('beritum/index');
        }
        else
        {            
            $data['_view'] = 'beritum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a beritum
     */
    function edit($id)
    {   
        // check if the beritum exists before trying to edit it
        $data['beritum'] = $this->Beritum_model->get_beritum($id);
        
        if(isset($data['beritum']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'judul' => $this->input->post('judul'),
					'content' => $this->input->post('content'),
					'gambar' => $this->input->post('gambar'),
					'date' => $this->input->post('date'),
                );

                $this->Beritum_model->update_beritum($id,$params);            
                redirect('beritum/index');
            }
            else
            {
                $data['_view'] = 'beritum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The beritum you are trying to edit does not exist.');
    } 

    /*
     * Deleting beritum
     */
    function remove($id)
    {
        $beritum = $this->Beritum_model->get_beritum($id);

        // check if the beritum exists before trying to delete it
        if(isset($beritum['id']))
        {
            $this->Beritum_model->delete_beritum($id);
            redirect('beritum/index');
        }
        else
            show_error('The beritum you are trying to delete does not exist.');
    }
    
}
