<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Galery extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Galery_model');
    } 

    /*
     * Listing of galery
     */
    function index()
    {
        $data['galery'] = $this->Galery_model->get_all_galery();
        
        $data['_view'] = 'galery/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new galery
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'judul' => $this->input->post('judul'),
				'link' => $this->input->post('link'),
            );
            
            $galery_id = $this->Galery_model->add_galery($params);
            redirect('galery/index');
        }
        else
        {            
            $data['_view'] = 'galery/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a galery
     */
    function edit($id)
    {   
        // check if the galery exists before trying to edit it
        $data['galery'] = $this->Galery_model->get_galery($id);
        
        if(isset($data['galery']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'judul' => $this->input->post('judul'),
					'link' => $this->input->post('link'),
                );

                $this->Galery_model->update_galery($id,$params);            
                redirect('galery/index');
            }
            else
            {
                $data['_view'] = 'galery/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The galery you are trying to edit does not exist.');
    } 

    /*
     * Deleting galery
     */
    function remove($id)
    {
        $galery = $this->Galery_model->get_galery($id);

        // check if the galery exists before trying to delete it
        if(isset($galery['id']))
        {
            $this->Galery_model->delete_galery($id);
            redirect('galery/index');
        }
        else
            show_error('The galery you are trying to delete does not exist.');
    }
    
}
