<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Galery_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get galery by id
     */
    function get_galery($id)
    {
        return $this->db->get_where('galery',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all galery
     */
    function get_all_galery()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('galery')->result_array();
    }
        
    /*
     * function to add new galery
     */
    function add_galery($params)
    {
        $this->db->insert('galery',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update galery
     */
    function update_galery($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('galery',$params);
    }
    
    /*
     * function to delete galery
     */
    function delete_galery($id)
    {
        return $this->db->delete('galery',array('id'=>$id));
    }
}
